### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by ewelinajozwik** [thehyve/transmart-lib#2]
README.md:
[transmart-proxy](https://github.com/thehyve/transmart-lib/blob/master/README.md#transmart-proxy) dependency mentiones `<artifactId>transmart-common</artifactId>` instead of `<artifactId>transmart-proxy</artifactId>`

**Comment by ewelinagr** [comment]
[FieldConstraint.java](https://github.com/thehyve/transmart-lib/blob/master/transmart-common/src/main/java/org/transmartproject/common/constraint/FieldConstraint.java#L38):
Error message may not be clear if the operator is missing.

**Comment by ewelinajozwik** [comment]
[TemporalConstraint](https://github.com/thehyve/transmart-lib/blob/master/transmart-common/src/main/java/org/transmartproject/common/constraint/TemporalConstraint.java):
`private Operator operator;` - add @NotNull? or assertion if the operator supports event type as in tranSMART?

**Comment by ewelinajozwik** [comment]
[Study](https://github.com/thehyve/transmart-lib/blob/master/transmart-common/src/main/java/org/transmartproject/common/dto/Study.java):
Missing Study blob (metadata)?

**Comment by ewelinajozwik** [comment]
[VisitDimensionElement](https://github.com/thehyve/transmart-lib/blob/master/transmart-common/src/main/java/org/transmartproject/common/dto/VisitDimensionElement.java):
Missing patientId.

**Comment by ewelinagr** [comment]
[CurrentUser](https://github.com/thehyve/transmart-lib/blob/master/transmart-proxy/src/main/java/org/transmartproject/proxy/security/CurrentUser.java#L27)
What is the purpose of `ROLE_ANONYMOUS`? 
Maybe usefull to add it to the README?
